services:
#  jaeger-all-in-one:
#    container_name: jaeger
#    image: jaegertracing/all-in-one:latest
#    restart: always
#    ports:
#      - "16686:16686"
#      - "14268"
#      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - "./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml"
    ports:
      - "4317:4317"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  service_a:
    build:
      dockerfile: go-service-a/Dockerfile
    ports:
      - "8082:8082"
    container_name: service_a

  service_b:
    build:
      dockerfile: go-service-b/Dockerfile
    ports:
      - "8081:8081"
    container_name: service_b